name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Install Wine32
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install wine32

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Update to Node.js version 16

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build:win

      - name: Read version from package.json
        id: version
        run: echo "::set-output name=version::$(jq -r '.version' package.json)"

      - name: Tag commit with version
        run: git tag v${{ steps.version.outputs.version }}

      - name: Push tag
        run: git push origin v${{ steps.version.outputs.version }}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            # Add other files to be included in the release
          tag_name: v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
